package sait.frms.problemdomain;

import sait.frms.manager.FlightManager;

/**
 * Reservation class which creates, sets and gets the information for Flight objects.
 * @author Allyssa Preece
 * @author Anusone Soula
 * @author Aiden Kopec
 * @version March 27, 2022
 */
public class Reservation {
    /**
     * The code generated by reservation.
     */
    private final String code;

    /**
     * The flightCode created by flights.
     */
    private final String flightCode;

    /**
     * The name of the airline.
     */
    private final String airline;

    /**
     * The name of the traveler.
     */
    private String name;

    /**
     * The citizenship of traveler.
     */
    private String citizenship;

    /**
     * The cost of the flight.
     */
    private final double cost;

    /**
     * If the traveler is active or not.
     */
    private boolean active;

    /**
     * Creates a reservation object based on user input.
     * 
     * @param code        The reservation code will be generated when a reservation
     *                    is created.
     * @param flightCode  The flight code the reservation is for.
     * @param airline     The airline who owns and operates the flight.
     * @param name        The name of the traveler.
     * @param citizenship The citizenship of the traveler.
     * @param cost        The cost of the reservation.
     * @param active      If the reservation is active or not.
     */
    public Reservation(String code, String flightCode, String airline, String name, String citizenship, double cost, boolean active) {
        this.code = code;
        this.flightCode = flightCode;
        this.airline = airline;
        this.name = name;
        this.citizenship = citizenship;
        this.cost = Math.round(cost * 100.00) / 100.00;
        this.active = active;
    }

    /**
     * Returns a String of the reservation code.
     * @return The reservation code.
     */
    public String getCode() {
        return code;
    }
    
    /**
     * Returns a String with the flight code.
     * @return The flight code.
     */
    public String getFlightCode() {
        return flightCode;
    }

    /**
     * Returns the name of the airline.
     * @return The name of the airline.
     */
    public String getAirline() {
        return airline;
    }
    
    /**
     * Returns the traveler's name.
     * @return The name of the traveler.
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the traveler's name.
     * @param name The name of the traveler.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Returns a String of the traveler's citizenship.
     * @return The traveler's citizenship.
     */
    public String getCitizenship() {
        return citizenship;
    }
    
    /**
     * Set the traveler's citizenship.
     * @param citizenship The citizenship of the traveler.
     */
    public void setCitizenship(String citizenship) {
        this.citizenship = citizenship;
    }

    /**
     * Returns the cost of the reservation.
     * @return The reservation cost.
     */
    public double getCost() {
        return cost;
    }
    
    /**
     * Returns a boolean depending on the state of the reservation.
     * @return A boolean whether the reservation is active or not.
     */
    public boolean isActive() {
        return active;
    }

    /**
     * Sets the reservation status.
     * @param active The status of the reservation.
     */
    public void setActive(boolean active) {
        for (Flight f : FlightManager.getFlights()) {
             if (active) {
                 f.setNumOfSeatsAvailable(f.getNumOfAvailableSeats() - 1);
             } else{
                 f.setNumOfSeatsAvailable(f.getNumOfAvailableSeats() + 1);
             }
         }
      
        this.active = active;
    }
    
    /**
     * Overridden toString() method for reservation objects.
     * @return The reservation details.
     */
    @Override
    public String toString() {
        return code;
    }
}
